on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello wordl action step
      id: hello
      uses: actions/hello-github-actions@v1
      with:
        who-to-greet: 'Donny'
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
